### ISSUE TITLE
Error while updating Forecast, please try again

### ISSUE THREAD

**Issue by WeberAlex** [dh4/WeatherRadar#13]
No matter the location, I receive an `Error while updating Forecast, please try again` message.

Android 10, F-Droid.

I registered to OpenWeather and used the API about 4 hours ago. I can see my locations from the Website.

**Comment by noyannus** [comment]
Same here.

On Website, my city is found. 
Photon API in RadarWeather finds it and it is saved to RW.
Error (localized) the same as above; no weather function.

RW 6.2 via F-Droid
Android 13 (as DivestOS 20-20230813).

---

Also, the pop-up with the error message should be large enough to hold the full text for all localizations. It does not even in landscape orientation; it always clips off the meaningful part (German, in this case).

---

EDIT: The perimeter/radius/..? search works, though. 
=> Users: Minimize search values for a crude workaround. 
=> Devs: This also shows that the cause is not a network error.

**Comment by dh4** [comment]
Hello,

This issue is for the wrong app. Are you looking for RadarWeather?
https://f-droid.org/packages/org.woheller69.weather/

Their issue tracker is here:
https://github.com/woheller69/weather/issues

**Comment by noyannus** [comment]
Can't answer that any more, I have switched to security/privacy hardened [DivestOS](https://divestos.org/) and only use a tightly restricted set of software sources. In case you are right I'm sorry for wasting your time.
